name: customer_app
description: "Taksibu Yolcu UygulamasÄ±"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  dio: ^5.9.0
  socket_io_client: ^3.1.2
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  flutter_secure_storage: ^9.2.4
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  uuid: ^4.5.2
  url_launcher: ^6.2.5
  intl: ^0.20.2
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.10


  # Firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.0
  easy_localization: ^3.0.7
  
  # Image Picker
  image_picker: ^1.0.7
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  json_serializable: ^6.11.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_logo_padded.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/splash_logo_padded.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo_padded.png
  branding: assets/images/splash_logo_padded.png
  color_dark: "#121212"
  image_dark: assets/images/splash_logo_padded.png
  
  android_12:
    image: assets/images/splash_logo_padded.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
